<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mtb</string>
		<string>mac</string>
	</array>
	<key>name</key>
	<string>Minitab</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment Line</string>
			<key>match</key>
			<string>((#).*\n?)</string>
			<key>name</key>
			<string>comment.line.number-sign.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Another test</string>
			<key>match</key>
			<string>\b(do|if|then|else|enddo|elseif|endif|while|endwhile)\b</string>
			<key>name</key>
			<string>keyword.control.flow.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Command</string>
			<key>match</key>
			<string>(^\w+)</string>
			<key>name</key>
			<string>support.class.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>subcommand</string>
			<key>match</key>
			<string>^\s\s[\w\-]+</string>
			<key>name</key>
			<string>support.function.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>strings</string>
			<key>match</key>
			<string>\"([^\"]*)\"</string>
			<key>name</key>
			<string>string.quoted.double.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>unquoted strings</string>
			<key>match</key>
			<string>\'([^\']*)\'</string>
			<key>name</key>
			<string>string.unquoted.single.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operator</string>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>arithmetic</string>
			<key>match</key>
			<string>\+|\-|\*|\&gt;|\&lt;|\/|\^|\*\*</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Semicolon</string>
			<key>match</key>
			<string>\;|\.</string>
			<key>name</key>
			<string>support.other.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numeric values</string>
			<key>match</key>
			<string>\b\d+</string>
			<key>name</key>
			<string>constant.numeric.float.minitab</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>arguments</string>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>variable.parameter.minitab</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.minitab</string>
	<key>uuid</key>
	<string>0c2ae734-a77d-4a02-9335-5ea8248df712</string>
</dict>
</plist>
